# -*- coding: utf-8 -*-
"""intelligent_girl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CIuJbqti5roBnj6TW4XTYjp5gx2PUV00
"""

# s = "574674546476"
s = input()
l = len(s)

dp = []

for i in range(l):
    dp.append(0)

if int(s[l-1])%2 == 0:
    dp[l-1] = 1

for i in range(l-1):
    dp[l-2-i] = dp[l-1-i]
    if int(s[l-2-i])%2 == 0:
        dp[l-2-i] = dp[l-2-i] + 1

print(*dp)